[package]
name = "manyzip"
version = "1.0.3"
edition = "2021"
license = "0BSD"
description = "Zip an arbitrary number of iterables"
repository = "https://github.com/yanqui-uxo/manyzip"
categories = ["no-std"]